# Generated by Django 5.2.4 on 2025-07-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="catalog/photos",
                verbose_name="Фотография",
            ),
        ),
    ]
