# Generated by Django 4.2.2 on 2025-08-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                choices=[(True, "Опубликовано"), (False, "Не опубликовано")],
                default=False,
                help_text="Отметьте для публикации",
                verbose_name="Опубликовано",
            ),
        ),
    ]
